@echo off
echo 正在准备部署到Railway...

echo 1. 关闭当前运行的服务器进程...
taskkill /f /im node.exe

echo 2. 进入项目目录...
cd /d %~dp0

echo 3. 安装Railway CLI（如果尚未安装）...
npm install -g @railway/cli

echo 4. 登录Railway（如果尚未登录）...
railway login

echo 5. 链接到Railway项目...
railway link

echo 6. 部署到Railway...
railway up

echo 部署完成！请查看Railway控制台获取更多信息。
pause 