[phases.setup]
nixPkgs = ["nodejs", "npm", "bash"]
aptPkgs = ["build-essential", "python3"]

[phases.install]
cmds = ["npm run install-all"]
cacheDirectories = [".npm", "node_modules", "client/node_modules", "server/node_modules"]

[phases.build]
cmds = ["chmod +x ./build.sh", "./build.sh"]
dependsOn = ["install"]

[start]
cmd = "npm start" 